USE [master]
GO

/****** Object:  Database [WebPrueba]    Script Date: 02/09/2019 11:27:09 a. m. ******/
CREATE DATABASE [WebPrueba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaWeb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PruebaWeb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaWeb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PruebaWeb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WebPrueba] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebPrueba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebPrueba] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebPrueba] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebPrueba] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebPrueba] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebPrueba] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebPrueba] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebPrueba] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebPrueba] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebPrueba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebPrueba] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebPrueba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebPrueba] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebPrueba] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebPrueba] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebPrueba] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebPrueba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebPrueba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebPrueba] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebPrueba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebPrueba] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebPrueba] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebPrueba] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebPrueba] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebPrueba] SET  MULTI_USER 
GO

ALTER DATABASE [WebPrueba] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebPrueba] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebPrueba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebPrueba] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebPrueba] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebPrueba] SET QUERY_STORE = OFF
GO

USE [WebPrueba]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [WebPrueba] SET  READ_WRITE 
GO

