//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPruebaData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WebPruebaEntities;
    
    public partial class WebPruebaBDEntities : DbContext
    {
        internal const string ConnectionStringName = "name=WebPruebaBDEntities";
        public WebPruebaBDEntities()
            : base("name=WebPruebaBDEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
