//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBASPNETMVCWCFSECIDEN.UsuariosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/WebPruebaEntities")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuId {
            get {
                return this.UsuIdField;
            }
            set {
                if ((this.UsuIdField.Equals(value) != true)) {
                    this.UsuIdField = value;
                    this.RaisePropertyChanged("UsuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuNombre {
            get {
                return this.UsuNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuNombreField, value) != true)) {
                    this.UsuNombreField = value;
                    this.RaisePropertyChanged("UsuNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuPassword {
            get {
                return this.UsuPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuPasswordField, value) != true)) {
                    this.UsuPasswordField = value;
                    this.RaisePropertyChanged("UsuPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosService.IUsuariosService")]
    public interface IUsuariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuariosResponse")]
        System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios>> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/CrearUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/CrearUsuariosResponse")]
        WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios CrearUsuarios(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/CrearUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/CrearUsuariosResponse")]
        System.Threading.Tasks.Task<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> CrearUsuariosAsync(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ActualizarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ActualizarUsuariosResponse")]
        bool ActualizarUsuarios(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios enitity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ActualizarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/ActualizarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuariosAsync(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios enitity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuariosResponse")]
        bool EliminarUsuarios(int usuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/EliminarUsuarios", ReplyAction="http://tempuri.org/IUsuariosService/EliminarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuariosAsync(int usuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarioById", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuarioByIdResponse")]
        System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> ObtenerUsuarioById(int usuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuariosService/ObtenerUsuarioById", ReplyAction="http://tempuri.org/IUsuariosService/ObtenerUsuarioByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios>> ObtenerUsuarioByIdAsync(int usuarioId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosServiceChannel : WEBASPNETMVCWCFSECIDEN.UsuariosService.IUsuariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosServiceClient : System.ServiceModel.ClientBase<WEBASPNETMVCWCFSECIDEN.UsuariosService.IUsuariosService>, WEBASPNETMVCWCFSECIDEN.UsuariosService.IUsuariosService {
        
        public UsuariosServiceClient() {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios>> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios CrearUsuarios(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios entity) {
            return base.Channel.CrearUsuarios(entity);
        }
        
        public System.Threading.Tasks.Task<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> CrearUsuariosAsync(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios entity) {
            return base.Channel.CrearUsuariosAsync(entity);
        }
        
        public bool ActualizarUsuarios(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios enitity) {
            return base.Channel.ActualizarUsuarios(enitity);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuariosAsync(WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios enitity) {
            return base.Channel.ActualizarUsuariosAsync(enitity);
        }
        
        public bool EliminarUsuarios(int usuarioId) {
            return base.Channel.EliminarUsuarios(usuarioId);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuariosAsync(int usuarioId) {
            return base.Channel.EliminarUsuariosAsync(usuarioId);
        }
        
        public System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios> ObtenerUsuarioById(int usuarioId) {
            return base.Channel.ObtenerUsuarioById(usuarioId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WEBASPNETMVCWCFSECIDEN.UsuariosService.Usuarios>> ObtenerUsuarioByIdAsync(int usuarioId) {
            return base.Channel.ObtenerUsuarioByIdAsync(usuarioId);
        }
    }
}
